/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import DAO.ctrlMontagem;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import modelo.Montagem;

/**
 *
 * @author P4ul0
 */
public class FMontagem extends javax.swing.JFrame {

    ctrlMontagem ctrlM = new ctrlMontagem();
    Montagem m = new Montagem();
    
    public void limpar(){
        edtCodigo.setText("");
        cbMonitor.setSelectedIndex(-1);
        cbTeclado.setSelectedIndex(-1);
        cbGabinete.setSelectedIndex(-1);
        cbImpressora.setSelectedIndex(-1);
        cbScanner.setSelectedIndex(-1);
        cbMouse.setSelectedIndex(-1);
    }
    
    public void liberar(){
        edtCodigo.setEnabled(true);
        cbMonitor.setEnabled(true);
        cbTeclado.setEnabled(true);
        cbGabinete.setEnabled(true);
        cbImpressora.setEnabled(true);
        cbScanner.setEnabled(true);
        cbMouse.setEnabled(true);
        btnConsultar.setEnabled(true);
        btnIncluir.setEnabled(true);
        btnAlterar.setEnabled(true);
        btnExcluir.setEnabled(true);       
    }
    
    public void resetar() {
        edtCodigo.setEnabled(true);
        cbMonitor.setEnabled(false);
        cbTeclado.setEnabled(false);
        cbGabinete.setEnabled(false);
        cbImpressora.setEnabled(false);
        cbScanner.setEnabled(false);
        cbMouse.setEnabled(false);
        btnNovo.setEnabled(true);
        btnConsultar.setEnabled(true);
        btnIncluir.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
    }
    
    public void prepararCb() {
        cbMonitor.setSelectedItem("Selecione Monitor");
        cbTeclado.setSelectedItem("Selecione Teclado");
        cbGabinete.setSelectedItem("Selecione Gabinete");
        cbImpressora.setSelectedItem("Selecione Impressora");
        cbScanner.setSelectedItem("Selecione Scanner");
        cbMouse.setSelectedItem("Selecione Mouse");
    }
    
    public void carregarCb(String tabela, JComboBox cb) {
        ResultSet rs;
        rs=ctrlM.encontrarNum_comp(tabela); 
        try { 
            while(rs.next()){ 
                int cod = rs.getInt(1);
                String fabricante = ctrlM.encontrarFabricante(cod);
                String descricao = ctrlM.encontrarDescricao(cod);
                
                cb.addItem(" "+fabricante+" -"+descricao+"."); 
                cb.updateUI(); 

            } 
        } catch (SQLException ex) { 
                Logger.getLogger(FMontagem.class.getName()).log(Level.SEVERE, null, ex); 
        }
    }
    
    public String pegarFabricante (JComboBox cb) {
        String texto = cb.getSelectedItem()+"";  
        int posicao1 = texto.indexOf(" ") + 1;  
        int posicao2 = texto.indexOf(" -", posicao1);  
        String selecao = texto.substring(posicao1, posicao2);
        
        return selecao;
    }
    
    public String pegarDescricao (JComboBox cb) {
        String texto = cb.getSelectedItem()+"";  
        int posicao1 = texto.indexOf("-") + 1;  
        int posicao2 = texto.indexOf(".", posicao1);  
        String selecao = texto.substring(posicao1, posicao2);
        
        return selecao;
    }
    
    /**
     * Creates new form FMontagem
     */
    public FMontagem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbMonitor = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbTeclado = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        cbGabinete = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        cbImpressora = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        cbScanner = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        cbMouse = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        edtCodigo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnIncluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Montagem de Maquina");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cbMonitor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione Monitor" }));
        cbMonitor.setSelectedIndex(-1);

        jLabel2.setText("Monitor:");

        jLabel3.setText("Teclado:");

        cbTeclado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione Teclado" }));
        cbTeclado.setSelectedIndex(-1);
        cbTeclado.setToolTipText("");

        jLabel4.setText("Gabinete:");

        cbGabinete.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione Gabinete" }));
        cbGabinete.setSelectedIndex(-1);

        jLabel5.setText("Impressora:");

        cbImpressora.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione Impressora" }));
        cbImpressora.setSelectedIndex(-1);

        jLabel6.setText("Scanner:");

        cbScanner.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione Scanner" }));
        cbScanner.setSelectedIndex(-1);

        jLabel7.setText("Mouse:");

        cbMouse.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione Mouse" }));
        cbMouse.setSelectedIndex(-1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbMonitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbTeclado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbGabinete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbImpressora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbScanner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbMouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbMonitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbTeclado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbGabinete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbImpressora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbScanner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbMouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cbMonitor.getAccessibleContext().setAccessibleName("Selecione o Monitor");
        cbTeclado.getAccessibleContext().setAccessibleName("Selecione o Teclado");

        jLabel1.setText("Código Máquina:");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnIncluir.setText("Incluir");
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIncluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConsultar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIncluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu2.setText("Arquivo");

        jMenuItem1.setText("Resetar Campos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Sair");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(edtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(edtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        limpar();
        resetar();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        FMontagem.this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
        m.setCodigo(Integer.parseInt(edtCodigo.getText()));
        m.setCod_monitor(ctrlM.encontrarCodigo(pegarFabricante(cbMonitor),"monitor",pegarDescricao(cbMonitor)));
        m.setCod_teclado(ctrlM.encontrarCodigo(pegarFabricante(cbTeclado),"teclado",pegarDescricao(cbTeclado)));
        m.setCod_gabinete(ctrlM.encontrarCodigo(pegarFabricante(cbGabinete),"gabinete",pegarDescricao(cbGabinete)));
        m.setCod_impressora(ctrlM.encontrarCodigo(pegarFabricante(cbImpressora),"impressora",pegarDescricao(cbImpressora)));
        m.setCod_scanner(ctrlM.encontrarCodigo(pegarFabricante(cbScanner),"scanner",pegarDescricao(cbScanner)));
        m.setCod_mouse(ctrlM.encontrarCodigo(pegarFabricante(cbMouse),"mouse",pegarDescricao(cbMouse)));
        int erro=ctrlM.inserirMaquina(m);
        if(erro==0){
            JOptionPane.showMessageDialog(null,"Inclusão concluída com êxito!");
            limpar();
            resetar();
        }else
        JOptionPane.showMessageDialog(null,"Falha na inclusão !");
    }//GEN-LAST:event_btnIncluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        m.setCodigo(Integer.parseInt(edtCodigo.getText()));
        m.setCod_monitor(ctrlM.encontrarCodigo(pegarFabricante(cbMonitor),"monitor",pegarDescricao(cbMonitor)));
        m.setCod_teclado(ctrlM.encontrarCodigo(pegarFabricante(cbTeclado),"teclado",pegarDescricao(cbTeclado)));
        m.setCod_gabinete(ctrlM.encontrarCodigo(pegarFabricante(cbGabinete),"gabinete",pegarDescricao(cbGabinete)));
        m.setCod_impressora(ctrlM.encontrarCodigo(pegarFabricante(cbImpressora),"impressora",pegarDescricao(cbImpressora)));
        m.setCod_scanner(ctrlM.encontrarCodigo(pegarFabricante(cbScanner),"scanner",pegarDescricao(cbScanner)));
        m.setCod_mouse(ctrlM.encontrarCodigo(pegarFabricante(cbMouse),"mouse",pegarDescricao(cbMouse)));
        int resp=JOptionPane.showConfirmDialog(null,"Deseja realmente alterar os dados da maquina "+m.getCodigo()+" ?");
        if(resp==JOptionPane.YES_OPTION){
            int erro=ctrlM.alterarMaquina(m);
            if(erro==0){
                JOptionPane.showMessageDialog(null,"Alteração concluída com êxito");
                limpar();
                resetar();
            }else
            JOptionPane.showMessageDialog(null,"Falha na alteração");
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        m.setCodigo(Integer.parseInt(edtCodigo.getText()));
        int resp=JOptionPane.showConfirmDialog(null,"Deseja resalmente exlcuir a maquina "+m.getCodigo()+" ?");
        if (resp==JOptionPane.YES_OPTION){
            resp=JOptionPane.showConfirmDialog(null,"TODOS os dados referentes a maquina "+m.getCodigo()+" serão apagados, voce tem CERTEZA ?!");
            if (resp==JOptionPane.YES_OPTION){
            int erro=ctrlM.excluirMaquina(m);
            if(erro==0){
                JOptionPane.showMessageDialog(null,"Exclusão concluída com êxito");
                limpar();
                resetar();
            }else
            JOptionPane.showMessageDialog(null,"Falha na exclusão");
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        int cod=Integer.parseInt(edtCodigo.getText());
        int rc=ctrlM.consultar(cod, m);
        if (rc!=0)JOptionPane.showMessageDialog(null,"Maquina de código "+cod+" não encontrada !");
        else {
            edtCodigo.setText(String.valueOf(m.getCodigo()));
            cbMonitor.setSelectedItem(" "+ctrlM.encontrarFabricanteCod(m.getCod_monitor(), "monitor")+" -"+ctrlM.encontrarDescricaoCod(m.getCod_monitor(), "monitor")+".");
            cbTeclado.setSelectedItem(" "+ctrlM.encontrarFabricanteCod(m.getCod_teclado(), "teclado")+" -"+ctrlM.encontrarDescricaoCod(m.getCod_teclado(), "teclado")+".");
            cbGabinete.setSelectedItem(" "+ctrlM.encontrarFabricanteCod(m.getCod_gabinete(), "gabinete")+" -"+ctrlM.encontrarDescricaoCod(m.getCod_gabinete(), "gabinete")+".");
            cbImpressora.setSelectedItem(" "+ctrlM.encontrarFabricanteCod(m.getCod_impressora(), "impressora")+" -"+ctrlM.encontrarDescricaoCod(m.getCod_impressora(), "impressora")+".");
            cbScanner.setSelectedItem(" "+ctrlM.encontrarFabricanteCod(m.getCod_scanner(), "scanner")+" -"+ctrlM.encontrarDescricaoCod(m.getCod_scanner(), "scanner")+".");
            cbMouse.setSelectedItem(" "+ctrlM.encontrarFabricanteCod(m.getCod_mouse(), "mouse")+" -"+ctrlM.encontrarDescricaoCod(m.getCod_mouse(), "mouse")+".");
            System.out.println(" "+ctrlM.encontrarFabricanteCod(m.getCod_mouse(), "mouse")+" -"+ctrlM.encontrarDescricaoCod(m.getCod_mouse(), "mouse")+".");
            liberar();
            edtCodigo.setEnabled(false);
            btnIncluir.setEnabled(false);
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        limpar();
        liberar();
        prepararCb();
        edtCodigo.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnConsultar.setEnabled(false);
        edtCodigo.setText(String.valueOf(ctrlM.calcChave()));
        btnNovo.setEnabled(false);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        carregarCb("monitor",cbMonitor);
        carregarCb("teclado",cbTeclado);
        carregarCb("gabinete",cbGabinete);
        carregarCb("impressora",cbImpressora);
        carregarCb("scanner",cbScanner);
        carregarCb("mouse",cbMouse);
        resetar();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FMontagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FMontagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FMontagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FMontagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FMontagem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JComboBox cbGabinete;
    private javax.swing.JComboBox cbImpressora;
    private javax.swing.JComboBox cbMonitor;
    private javax.swing.JComboBox cbMouse;
    private javax.swing.JComboBox cbScanner;
    private javax.swing.JComboBox cbTeclado;
    private javax.swing.JTextField edtCodigo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
